### ISSUE TITLE
map.get()?

### ISSUE THREAD

**Issue by corpsmoderne** [KnorrFG/axum_vs_nginx#1]
Hey just coming from your blog-post about this and didn't found another way to get in touch :)

Was wondering if there was a reason here to iterate on all the elements of the HashMap ? replacing the for loop with 
`if let Some(router) = map.get(&hostname)` or something like that should have the same effect with better performance, but maybe I'm missing something?
 
https://github.com/KnorrFG/axum_vs_nginx/blob/ea82235dd27617fe88f7b4626cde9a943f8ab838/src/main.rs#L190

**Comment by KnorrFG** [comment]
Hey, no problem ^^

You are right, that could be done. This is a symptom of how the code came to be.
