### ISSUE TITLE
Axum based web server

### ISSUE THREAD

**Issue by nicolaspernoud** [KnorrFG/axum_vs_nginx#2]
Hello,
I just had a look at your blog post (https://felix-knorr.net/posts/2024-10-13-replacing-nginx-with-axum.html).
You may want to have a look at : https://github.com/nicolaspernoud/atrium .
It's a web server that i made with axum that has a lot of what you describe in the post... And that can be configured by GUI or yaml file...
Best regards.

**Comment by KnorrFG** [comment]
Cool project, but the whole point of the the article was to have code-as-config, which basically rules out using a webserver ^^
